### ISSUE TITLE
schematics

### ISSUE THREAD

**Issue by claude1000** [Patave/AutodiDICE#1]
Dear
could you post the schematics of the dice ? 

nice job
thanks 
Claude

**Comment by Patave** [comment]
> Dear
> 
> could you post the schematics of the dice ? 
> 
> 
> 
> nice job
> 
> thanks 
> 
> Claude

Hi Claude, 
I will do.
But you have the gerber files if you want.
Patrick

**Comment by Patave** [comment]
Claude, The schematic is now available

**Comment by claude1000** [comment]
thanks a lot
