### ISSUE TITLE
Random not working?

### ISSUE THREAD

**Issue by rods** [Patave/AutodiDICE#3]
I tried using ATTiny85 and ATTiny14 but the result is always 2, 4 or 6. There are no odd ones. 
Compiled the v2 for both and v1 for ATTiny85. Results are the same

**Comment by Patave** [comment]
Hi @rods , no reasons to randomize only for even numbers. Or you are very lucky.
I think that you have an hardware issue with the middle led.

**Comment by rods** [comment]
Sorry @Patave ! shame on me!!! The center LED was down...fixed! This project is awesome...

**Comment by Patave** [comment]
Great
